### ISSUE TITLE
On Stress tests found: timeouts

### ISSUE THREAD

**Issue by ibolmo** [ibolmo/cametrics#6]
```
05-25 01:02AM 14.123 /ahBjYW1ldHJpY3Mtc3RyZXNzchULEg5teWFwcF9jYW1wYWlnbhjpBww/contributions/time 500 4155ms 8025cpu_ms 8012api_cpu_ms 0kb cametrics-stress.appspot.com gzip(gfe)
76.73.53.91 - - [25/May/2009:01:02:18 -0700] "POST /ahBjYW1ldHJpY3Mtc3RyZXNzchULEg5teWFwcF9jYW1wYWlnbhjpBww/contributions/time HTTP/1.1" 500 0 - "gzip(gfe)" "cametrics-stress.appspot.com"
E 05-25 01:02AM 18.276
<class 'google.appengine.api.datastore_errors.Timeout'>: 
Traceback (most recent call last):
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/appenginepatch/main.py", line 26, in real_main
    util.run_wsgi_app(application)
  File "/base/python_lib/versions/1/google/appengine/ext/webapp/util.py", line 76, in run_wsgi_app
    result = application(env, _start_response)
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/zip-packages/django-1.0.2.zip/django/core/handlers/wsgi.py", line 239, in __call__
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/zip-packages/django-1.0.2.zip/django/core/handlers/base.py", line 67, in get_response
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/appenginepatch/ragendja/sites/dynamicsite.py", line 21, in process_request
    site = Site.all().filter('domain =', domain).get()
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 1382, in get
    results = self.fetch(1)
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 1426, in fetch
    raw = self._get_query().Get(limit, offset)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 964, in Get
    return self._Run(limit, offset)._Next(limit)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 908, in _Run
    _ToDatastoreError(err)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 2020, in _ToDatastoreError
    raise errors[err.application_error](err.error_detail)
```

**Comment by ibolmo** [comment]
From [this](http://groups.google.com/group/google-appengine/browse_thread/thread/df4704b2d3c2f65c/06f3f40e5c837b07?show_docid=06f3f40e5c837b07#):

_Nick Johnson  (Apr 23, 2:23 am)_

... If the **two conflict, one of them will get in first, and the other will be failed** and automatically retry. It should take substantially higher contention to cause this. As I mentioned, though, it's possible this is happening due to timeouts. ... if this is real contention, you'd be best to **tell the client to come back later, since retrying will just increase contention further**. If it's **due to timeouts and other externalfactors, though, retrying would be preferable.**

**Comment by ibolmo** [comment]
Need to investigate what can be done to permit **all** data to be saved.
