### ISSUE TITLE
On stress test found: contention 

### ISSUE THREAD

**Issue by ibolmo** [ibolmo/cametrics#7]
```
05-25 01:02AM 19.176 /ahBjYW1ldHJpY3Mtc3RyZXNzchULEg5teWFwcF9jYW1wYWlnbhjpBww/356996016212614/contributions/type 200 2726ms 1032cpu_ms 900api_cpu_ms 2kb cametrics-stress.appspot.com gzip(gfe)
76.73.53.91 - - [25/May/2009:01:02:21 -0700] "POST /ahBjYW1ldHJpY3Mtc3RyZXNzchULEg5teWFwcF9jYW1wYWlnbhjpBww/356996016212614/contributions/type HTTP/1.1" 200 2010 - "gzip(gfe)" "cametrics-stress.appspot.com"
E 05-25 01:02AM 21.835
Exception in request:
Traceback (most recent call last):
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/zip-packages/django-1.0.2.zip/django/core/handlers/base.py", line 86, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/myapp/views.py", line 68, in measurements
    if (not datum.put()):
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/appenginepatch/appenginepatcher/patch.py", line 434, in put
    created=created, raw=raw)
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/zip-packages/django-1.0.2.zip/django/dispatch/dispatcher.py", line 148, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/myapp/models.py", line 106, in cb_calc_statistic
    if (stat.get(datum.type).calculate(datum) is not False):
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/myapp/stat.py", line 74, in calculate
    cls.tally(stats = datum.stats, name = 'hits', index = datum.value)
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/myapp/stat.py", line 58, in tally
    if (not hist.put()):
  File "/base/data/home/apps/cametrics-stress/1.333693860431221035/common/appenginepatch/appenginepatcher/patch.py", line 432, in put
    result = old_put(self, *args, **kwargs)
  File "/base/python_lib/versions/1/google/appengine/ext/db/__init__.py", line 696, in put
    return datastore.Put(self._entity)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 166, in Put
    raise _ToDatastoreError(err)
  File "/base/python_lib/versions/1/google/appengine/api/datastore.py", line 2020, in _ToDatastoreError
    raise errors[err.application_error](err.error_detail)
TransactionFailedError: too much contention on these datastore entities. please try again.
```

**Comment by ibolmo** [comment]
Closed. #6 and #7 are same errors. TransactionFailedError can occur due to timeouts [see](http://groups.google.com/group/google-appengine/browse_thread/thread/df4704b2d3c2f65c/06f3f40e5c837b07?show_docid=06f3f40e5c837b07#) for more information.
